/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=presence-worker/wrangler.jsonc --include-runtime=false presence-worker/worker-configuration.d.ts` (hash: 73f8a595e77f3a24188dfe64348592fb)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "http://localhost:4321,http://127.0.0.1:4321,https://rudeus.in,https://www.rudeus.in,https://portfolio-rudy200.vercel.app,https://portfolio-*-rudy200.vercel.app";
	PRESENCE: DurableObjectNamespace<import("./src/index").Presence>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Presence";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
